apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 1  # Number of desired pod replicas
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: rmettadocker/harness-ci-bootcamp:latest
        ports:
        - containerPort: 8080  # Port your Java app listens to
        env:
        - name: JAVA_OPTS  # Optional: set JVM options
          value: "-Xmx512m -Xms256m"
        resources:  # Resource requests and limits
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
